# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - staging.staydrysystems.com
      - staydry-staging.cimolini.com
    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:cimocimocimo/staydrysystems.com.git
    branch: master
    # repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo (above) if it is not the root (like the roots-example-project structure)

    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://staging.staydrysystems.com
      wp_siteurl: http://staging.staydrysystems.com/wp
      wp_env: staging
      db_name: staydry_staging_db
      db_user: staydry_staging_dbuser
      # Define the following variables in group_vars/staging/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
