# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - canonical: staydry.local
        redirects:
          - www.staydry.local

    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: StayDry Systems
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: staydry_dev
      db_user: staydry_dev_dbuser

  hollyharper.com:
    site_hosts:
      - canonical: hollyharper.local
    local_path: ../../Sites/hollyharper.com
    site_install: true
    site_title: Holly Harper Real Estate
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: hollyharper_dev
      db_user: hollyharper_dev_dbuser

  rodcointeriors.com:
    site_hosts:
      - canonical: rodco.local
    local_path: ../../Sites/rodcointeriors.com/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Rodco Interiors
    env:
      db_name: rodcointeriors_dev
      db_user: rodcointeriors_dev_dbuser

  emma.cimolini.com:
    site_hosts:
      - canonical: emma.local
    local_path: ../../Sites/emma.cimolini.com/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Emma Harper-Cimolini
    env:
      db_name: emma_dev
      db_user: emma_dev_user

  victoriadahliasociety.org:
    site_hosts:
      - canonical: dahlia.local
    local_path: ../../Sites/victoriadahliasociety.org/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Victoria Dahlia Society
    env:
      db_name: dahlia_dev
      db_user: dahlia_dev_user

  trevorball.com:
    site_hosts:
      - canonical: trevor.local
    local_path: ../../Sites/trevorball.com/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Trevor Ball Photography
    env:
      db_name: trevor_ball_dev
      db_user: trevor_ball_dev_user

  catfoodpuzzles.com:
    site_hosts:
      - canonical: catfoodpuzzles.local
    local_path: ../../Sites/catfoodpuzzles.com/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Cat Food Puzzles
    env:
      db_name: catfoodpuzzles_dev
      db_user: catfoodpuzzles_dev_user
