# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - canonical: staydry.dev
        redirects:
          - www.staydry.dev

    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: StayDry Systems
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: staydry_dev
      db_user: staydry_dev_dbuser

  hollyandjohn.ca:
    site_hosts:
      - canonical: hollyandjohn.dev
    local_path: ../../Sites/hollyandjohn.ca
    site_install: true
    site_title: Holly & John Real Estate
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: hollyandjohn_dev
      db_user: hollyandjohn_dev_dbuser

  yunustech.com:
    site_hosts:
      - canonical: yunustech.dev
    local_path: ../../Sites/yunustech.com/local/
    site_title: Yunustech Site
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: yunustech_dev
      db_user: yunustech_dev_dbuser

  hollyharper.com:
    site_hosts:
      - canonical: hollyharper.dev
    local_path: ../../Sites/hollyharper.com/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Holly Harper Real Estate
    env:
      db_name: hollyharper_dev
      db_user: hollyharper_dev_dbuser
