# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - staydry.dev
    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: StayDry Systems
    admin_user: admin
    # admin_password: (defined in group_vars/development/vault.yml)
    admin_email: aaron@cimolini.com
    initial_permalink_structure: /%postname%/ # applied only at time of WP install and when `site_install: true`
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://staydry.dev
      wp_siteurl: http://staydry.dev/wp
      wp_env: development
      db_name: staydry_dev
      db_user: staydry_dev_dbuser
      # db_password: (defined in group_vars/development/vault.yml)
  hollyandjohn.ca:
    site_hosts:
      - hollyandjohn.dev
    local_path: ../../Sites/hollyandjohn.ca
    site_install: true
    site_title: Holly & John Real Estate
    admin_user: admin
    admin_email: aaron@cimolini.com
    initial_permalink_structure: /%postname%/ # applied only at time of WP install and when `site_install: true`
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://hollyandjohn.dev
      wp_siteurl: http://hollyandjohn.dev/wp
      wp_env: development
      db_name: hollyandjohn_dev
      db_user: hollyandjohn_dev_dbuser

