# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - canonical: staydry.dev
        redirects:
          - www.staydry.dev

    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: StayDry Systems
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: staydry_dev
      db_user: staydry_dev_dbuser

  hollyharper.com:
    site_hosts:
      - canonical: hollyharper.dev
    local_path: ../../Sites/hollyharper.com
    site_install: true
    site_title: Holly Harper Real Estate
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_env: development
      db_name: hollyharper_dev
      db_user: hollyharper_dev_dbuser

  rodcointeriors.com:
    site_hosts:
      - canonical: rodco.dev
    local_path: ../../Sites/rodcointeriors.com/
    admin_email: aaron@cimolini.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
    site_title: Rodco Interiors
    env:
      db_name: rodcointeriors_dev
      db_user: rodcointeriors_dev_dbuser
