# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - canonical: staydrysystems.com
        redirects:
          - www.staydrysystems.com
          - staydry-production.cimolini.com
    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:cimocimocimo/staydrysystems.com.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: true
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://staydrysystems.com
      wp_siteurl: http://staydrysystems.com/wp
      wp_env: production
      db_name: staydry_prod_db
      db_user: staydry_prod_dbuser
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
  hollyandjohn.ca:
    site_hosts:
      - canonical: hollyandjohn.ca
        redirects:
          - www.hollyandjohn.ca
          - production.hollyandjohn.ca
    local_path: ../../Sites/hollyandjohn.ca
    repo: git@github.com:cimocimocimo/hollyandjohn.ca.git
    branch: master

    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://hollyandjohn.ca
      wp_siteurl: http://hollyandjohn.ca/wp
      wp_env: production
      db_name: hollyandjohn_production_db
      db_user: hollyandjohn_production_dbuser
      # Define the following variables in group_vars/staging/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
