# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  staydrysystems.com:
    site_hosts:
      - canonical: staydrysystems.com
        redirects:
          - www.staydrysystems.com
          - staydry-production.cimolini.com
    local_path: ../../Sites/staydrysystems.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:cimocimocimo/staydrysystems.com.git
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: true
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://staydrysystems.com
      wp_siteurl: http://staydrysystems.com/wp
      wp_env: production
      db_name: staydry_prod_db
      db_user: staydry_prod_dbuser

  hollyharper.com:
    site_hosts:
      - canonical: hollyharper.com
        redirects:
          - hollyandjohn.ca
          - www.hollyandjohn.ca
          - www.hollyharper.com
    local_path: ../../Sites/hollyandjohn.ca
    repo: git@github.com:cimocimocimo/hollyandjohn.ca.git
    branch: master
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://hollyharper.com
      wp_siteurl: http://hollyharper.com/wp
      wp_env: production
      db_name: hollyandjohn_production_db
      db_user: hollyandjohn_production_dbuser
